name: daily_planner
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  lottie: ^2.7.0
  font_awesome_flutter: ^10.7.0
  date_time_format: ^2.0.1
  intl: ^0.19.0
  uuid: ^4.2.2
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/ToDo.png
   - assets/animation/Animation - 1727165002975.json
